long_string_data = """
player1 win(contact), robot(pd), step = 42
player1 win(contact), robot, step = 289
player1 win(contact), robot(pd), step = 148
player1 win(contact), robot(pd), step = 880
time over(   r lose), robot, step = 1001
player1 win(contact), robot(pd), step = 124
player1 win(out    ), robot, step = 213
player2 win(contact), robot, step = 954
player1 win(contact), robot, step = 301
time over(    r win), robot, step = 1001
time over(   r lose), robot, step = 1001
player1 win(out    ), robot, step = 196
time over(    r win), robot, step = 1001
player1 win(contact), robot(pd), step = 297
player2 win(contact), robot, step = 41
time over(    r win), robot, step = 1001
player1 win(contact), robot(pd), step = 138
player1 win(contact), robot(pd), step = 725
player1 win(out    ), robot, step = 612
player1 win(out    ), robot, step = 212
time over(    r win), robot(pd), step = 1001
player1 win(contact), robot(pd), step = 168
player1 win(contact), robot, step = 667
time over(    r win), robot(pd), step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 109
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 361
player1 win(out    ), robot, step = 130
time over(    r win), robot, step = 1001
time over(   r lose), robot, step = 1001
player1 win(contact), robot, step = 786
player1 win(contact), robot, step = 275
player1 win(contact), robot, step = 303
time over(    r win), robot, step = 1001
player2 win(out    ), robot, step = 355
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 133
time over(    r win), robot, step = 1001
time over(    r win), robot(pd), step = 1001
player1 win(contact), robot, step = 152
player2 win(contact), robot, step = 829
time over(   r lose), robot, step = 1001
player1 win(out    ), robot, step = 158
time over(   r lose), robot, step = 1001
player1 win(contact), robot, step = 217
player2 win(out    ), robot, step = 539
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 280
player1 win(contact), robot(pd), step = 157
player1 win(contact), robot, step = 252
time over(   r lose), robot, step = 1001
player2 win(contact), robot, step = 48
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 238
player1 win(contact), robot, step = 831
player1 win(contact), robot, step = 193
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 625
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 194
player1 win(contact), robot, step = 339
player1 win(contact), robot, step = 387
player2 win(contact), robot, step = 653
time over(    r win), robot, step = 1001
player2 win(contact), robot, step = 542
player1 win(contact), robot, step = 199
player1 win(contact), robot, step = 425
time over(   r lose), robot, step = 1001
player1 win(contact), robot(pd), step = 49
player1 win(contact), robot, step = 321
player1 win(contact), robot(pd), step = 168
time over(    r win), robot(pd), step = 1001
player1 win(contact), robot(pd), step = 201
time over(    r win), robot, step = 1001
player2 win(out    ), robot, step = 537
player1 win(out    ), robot, step = 521
player1 win(contact), robot, step = 414
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player2 win(contact), robot(pd), step = 208
player1 win(contact), robot, step = 646
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 816
player1 win(contact), robot, step = 269
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 468
player1 win(contact), robot, step = 571
player1 win(contact), robot, step = 228
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 714
time over(    r win), robot, step = 1001
player2 win(contact), robot, step = 567
player2 win(out    ), robot, step = 868
time over(   r lose), robot, step = 1001
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 750
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 300
player1 win(contact), robot(pd), step = 262
time over(   r lose), robot, step = 1001
time over(   r lose), robot, step = 1001
time over(    r win), robot(pd), step = 1001
player2 win(contact), robot, step = 933
player1 win(out    ), robot, step = 237
player1 win(contact), robot(pd), step = 70
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 695
player1 win(contact), robot, step = 353
player1 win(contact), robot, step = 278
player1 win(contact), robot, step = 197
player1 win(out    ), robot, step = 700
player2 win(out    ), robot, step = 943
player1 win(out    ), robot, step = 395
player1 win(contact), robot, step = 840
player1 win(contact), robot, step = 441
time over(    r win), robot(pd), step = 1001
player1 win(contact), robot, step = 423
player1 win(out    ), robot, step = 813
player1 win(contact), robot, step = 348
player1 win(out    ), robot, step = 510
player1 win(contact), robot, step = 274
player1 win(contact), robot, step = 125
player1 win(out    ), robot, step = 710
player1 win(contact), robot, step = 263
player1 win(contact), robot, step = 351
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 157
player1 win(contact), robot, step = 85
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 317
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 727
player1 win(contact), robot, step = 421
player1 win(out    ), robot, step = 228
player1 win(contact), robot, step = 620
time over(    r win), robot, step = 1001
player2 win(contact), robot, step = 843
player2 win(contact), robot, step = 487
player1 win(contact), robot, step = 958
player1 win(out    ), robot, step = 425
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 403
player2 win(contact), robot, step = 747
time over(    r win), robot, step = 1001
time over(   r lose), robot, step = 1001
player1 win(out    ), robot, step = 817
time over(   r lose), robot, step = 1001
player1 win(contact), robot, step = 371
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 421
player1 win(contact), robot, step = 732
player1 win(contact), robot, step = 988
player2 win(out    ), robot, step = 902
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 295
player1 win(contact), robot, step = 149
time over(    r win), robot, step = 1001
player2 win(out    ), robot, step = 895
time over(   r lose), robot, step = 1001
player1 win(contact), robot(pd), step = 138
player1 win(out    ), robot, step = 602
time over(    r win), robot, step = 1001
player1 win(contact), robot(pd), step = 221
player1 win(out    ), robot, step = 310
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player2 win(contact), robot, step = 447
player1 win(contact), robot(pd), step = 220
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 840
time over(    r win), robot(pd), step = 1001
time over(    r win), robot, step = 1001
player2 win(contact), robot, step = 603
time over(   r lose), robot, step = 1001
time over(   r lose), robot, step = 1001
player2 win(contact), robot, step = 343
player1 win(contact), robot, step = 304
time over(   r lose), robot, step = 1001
player2 win(contact), robot, step = 192
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 318
player1 win(out    ), robot, step = 226
player1 win(contact), robot, step = 546
player2 win(contact), robot, step = 291
time over(    r win), robot, step = 1001
player1 win(contact), robot(pd), step = 214
player1 win(contact), robot, step = 711
player2 win(contact), robot, step = 158
time over(    r win), robot(pd), step = 1001
player1 win(contact), robot, step = 307
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 397
player1 win(out    ), robot, step = 868
player1 win(contact), robot, step = 275
time over(   r lose), robot, step = 1001
player1 win(contact), robot(pd), step = 78
time over(   r lose), robot, step = 1001
time over(    r win), robot(pd), step = 1001
player1 win(contact), robot, step = 311
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 440
time over(   r lose), robot, step = 1001
player1 win(contact), robot, step = 284
player1 win(out    ), robot, step = 788
player1 win(out    ), robot, step = 521
player1 win(contact), robot, step = 490
player1 win(contact), robot, step = 452
time over(    r win), robot, step = 1001
player2 win(contact), robot, step = 626
player1 win(contact), robot(pd), step = 170
player2 win(contact), robot, step = 708
time over(    r win), robot(pd), step = 1001
player1 win(contact), robot, step = 257
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 298
time over(    r win), robot, step = 1001
time over(   r lose), robot, step = 1001
player1 win(out    ), robot(pd), step = 215
player1 win(contact), robot, step = 695
player1 win(out    ), robot, step = 818
player1 win(contact), robot(pd), step = 70
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot(pd), step = 96
time over(   r lose), robot, step = 1001
time over(   r lose), robot, step = 1001
player1 win(out    ), robot, step = 213
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 598
time over(    r win), robot(pd), step = 1001
player1 win(contact), robot(pd), step = 170
time over(    r win), robot, step = 1001
player2 win(contact), robot, step = 805
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 342
player1 win(contact), robot(pd), step = 94
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 904
time over(   r lose), robot, step = 1001
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
time over(   r lose), robot, step = 1001
time over(   r lose), robot, step = 1001
player1 win(contact), robot, step = 316
player1 win(out    ), robot, step = 215
time over(    r win), robot, step = 1001
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 167
player1 win(contact), robot, step = 283
player1 win(contact), robot(pd), step = 552
player1 win(out    ), robot, step = 120
player1 win(contact), robot, step = 411
time over(   r lose), robot, step = 1001
player1 win(out    ), robot, step = 301
player1 win(contact), robot, step = 353
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot(pd), step = 42
player1 win(contact), robot, step = 53
time over(    r win), robot, step = 1001
player2 win(out    ), robot, step = 465
player1 win(contact), robot, step = 494
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 137
player1 win(out    ), robot, step = 179
player1 win(contact), robot(pd), step = 176
time over(    r win), robot, step = 1001
player1 win(contact), robot, step = 225
player1 win(contact), robot, step = 70
player1 win(contact), robot(pd), step = 135
player1 win(contact), robot, step = 211
player1 win(contact), robot, step = 606
player1 win(contact), robot, step = 693
player1 win(contact), robot, step = 233
player1 win(contact), robot, step = 298
player1 win(contact), robot, step = 187
player1 win(contact), robot, step = 259
time over(   r lose), robot, step = 1001
time over(   r lose), robot, step = 1001
player1 win(contact), robot, step = 515
time over(    r win), robot(pd), step = 1001
player1 win(contact), robot, step = 577
player1 win(contact), robot(pd), step = 242
time over(    r win), robot, step = 1001
player1 win(contact), robot(pd), step = 262
player1 win(contact), robot, step = 980
player1 win(out    ), robot, step = 397
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 432
player1 win(contact), robot(pd), step = 596
player2 win(out    ), robot, step = 204
time over(    r win), robot(pd), step = 1001
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot(pd), step = 281
player2 win(out    ), robot, step = 667
player2 win(contact), robot, step = 217
time over(   r lose), robot, step = 1001
player2 win(out    ), robot, step = 474
player1 win(contact), robot, step = 832
player1 win(out    ), robot, step = 740
player1 win(contact), robot, step = 728
player1 win(out    ), robot, step = 762
player1 win(contact), robot, step = 338
player2 win(out    ), robot, step = 371
time over(    r win), robot, step = 1001
player1 win(contact), robot(pd), step = 78
player1 win(contact), robot(pd), step = 77
player1 win(contact), robot, step = 279
time over(   r lose), robot, step = 1001
player1 win(contact), robot(pd), step = 293
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(contact), robot(pd), step = 249
player1 win(contact), robot(pd), step = 390
time over(    r win), robot(pd), step = 1001
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
time over(   r lose), robot, step = 1001
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 729
player1 win(out    ), robot, step = 807
time over(   r lose), robot, step = 1001
player1 win(contact), robot, step = 59
player1 win(contact), robot, step = 436
player2 win(contact), robot, step = 219
time over(    r win), robot, step = 1001
time over(   r lose), robot, step = 1001
player1 win(contact), robot, step = 242
player1 win(out    ), robot, step = 133
player2 win(contact), robot, step = 474
player2 win(out    ), robot, step = 552
time over(    r win), robot, step = 1001
player1 win(out    ), robot, step = 328
time over(    r win), robot, step = 1001
player2 win(contact), robot, step = 804
player1 win(contact), robot, step = 482
player1 win(out    ), robot, step = 872
time over(    r win), robot, step = 1001
time over(    r win), robot, step = 1001
"""
data_list = long_string_data.strip().splitlines()
# for line in data_list[:5]:
    # print(line)

player1_win_count = 0
player2_win_count = 0
time_over_win_count = 0
time_over_lose_count = 0
total_data_count = 0

for line in data_list:
    total_data_count += 1

    if "player1 win" in line.lower():
        player1_win_count += 1
    elif "player2 win" in line.lower():
        player2_win_count += 1
    elif "time over(    r win)" in line.lower():
        time_over_win_count += 1
    elif "time over(   r lose)" in line.lower():
        time_over_lose_count += 1

# Print the results
print("Player 1 wins:", player1_win_count)
print("Player 2 wins:", player2_win_count)
print("Time over (R win):", time_over_win_count)
print("Time over (R lose):", time_over_lose_count)
print("Total number of data:", total_data_count)